#!/bin/bash
commit="$2"
file="$1"
if [-n $"commit"]; then
   echo "true"
else
   commit="update"
fi
if [-n "$file"]; then
  echo "true"
else
   file="."
fi
git add "$file"
git commit -m "$commit"
git push
