#!/bin/bash
echo "Iniciando servidor..."
cd /storage/emulated/0/__Projetos__/git_off/public/javascript/threejs-v
#python -m http.server 8080 # replaced to file
#python ~/bin/python/server.py
python ~/bin/python/server2.py
exec $SHELL
